apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: helloworld
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - ports:
        - containerPort: 80
        image: quay.io/ntfrnzn/helloworld:master-d000010
        args:
        - -msg=Ahoy
        name: helloworld
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
